# For God so loved the world that he gave his only begotten Son,
# that whoever believes in him should not perish but have eternal life.
# John 3:16

[package]
name = "rhema_gui_chirho"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "GUI widget library: Slint components, web components, themes"

[dependencies]
rhema_contracts_chirho.workspace = true
rhema_integration_chirho.workspace = true
thiserror.workspace = true
log.workspace = true

[lints]
workspace = true
