# For God so loved the world that he gave his only begotten Son,
# that whoever believes in him should not perish but have eternal life.
# John 3:16

[package]
name = "rhema_query_chirho"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Query parser, IR, planner, and operators"
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
rhema_contracts_chirho.workspace = true
rhema_index_chirho.workspace = true
thiserror.workspace = true
anyhow.workspace = true
log.workspace = true
regex.workspace = true

[lints]
workspace = true
